<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="WebApplication14._Default" %>


  <asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

     <table style="width: 1000px;">
                <tr>
                    <td style="width: 123px" >
                        First Name</td>
                    <td style="width: 63px">
                        :</td>
                    <td style="width: 236px">
                        <asp:Label ID="fname" runat="server" Text="Label"></asp:Label></td>
                </tr>
                <tr>
                    <td style="width: 123px">
                        Last Name</td>
                    <td style="width: 63px">
                        :</td>
                    <td style="width: 236px">
                        <asp:Label ID="lname" runat="server" Text="Label"></asp:Label></td>
                </tr>
                <tr>
                      <td>
                     
                      </td>
                      <td>

                      </td>
                     
                </tr>
               <tr>
                    <td>

                    </td>
                   <td>

                   </td>
                    <td style="width:236px;" >
                          <asp:Button ID="Button1" runat="server" Text="view all student details " OnClick="viewDetails_Click"/>
                          <br />
                      </td>
               </tr>
           
         </table>
        <div id="Student">
            <asp:GridView ID="GridView1" runat="server"  style="height:200px; overflow:scroll" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
                onRowDeleting="GridView1_RowDeleting" onRowEditing="GridView1_RowEditing">
                <AlternatingRowStyle BackColor="#FFFFCC" Font-Bold="False" />
            </asp:GridView>
      </div>

</asp:Content>
